---
- name: Setup rc.local
  template:
    src: rc.local.j2
    dest: /etc/rc.local
    force: no
    mode: "u+rwx"
  notify: Restart rc-local
  when: custom_lb == "yes"


- name: Set net.ipv4.ip_forward=1
  become: yes
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Create kubeconfig directory
  file:
    path: ~/.kube
    state: directory
  when: inventory_hostname == groups[master_group][0]
  delegate_to: "{{ delegate_node }}"

## 更新这部分检查是否需要更新 config

- name: Clear local kubeconfig
  block:
    - shell: kubectl config unset users.{{ cluster_name }}
    - shell: kubectl config unset contexts.{{ cluster_name }}
    - shell: kubectl config unset clusters.{{ cluster_name }}
  when: inventory_hostname == groups[master_group][0]
  delegate_to: "{{ delegate_node }}"

- name: Setup first master
  command: k3sup install \
    --ip "{{ ansible_host }}" \
    --user "{{ ansible_user }}" \
    --context {{ cluster_name }} \
    --local-path ~/.kube/config --merge \
    --k3s-version "{{ k3s_version}}" \
    --k3s-extra-args '--tls-san {{ k8s_lb }} --tls-san {{ cluster_domain }} --node-label svccontroller.k3s.cattle.io/enablelb=true' \
    --ssh-key {{ ansible_ssh_private_key_file }} \
    --cluster
  when: inventory_hostname == groups[master_group][0]
  delegate_to: "{{ delegate_node }}"

- name: Setup other masters
  throttle: 1
  command: k3sup join \
    --ip "{{ ansible_host }}" \
    --user "{{ ansible_user }}" \
    --server-user "{{ ansible_user }}" \
    --server-ip {{ hostvars[groups[master_group][0]]['ansible_host'] }} \
    --k3s-version "{{ k3s_version}}" \
    --k3s-extra-args '--tls-san {{ k8s_lb }} --tls-san {{ cluster_domain }} --node-label svccontroller.k3s.cattle.io/enablelb=true' \
    --ssh-key {{ ansible_ssh_private_key_file }} \
    --server
  when: inventory_hostname != groups[master_group][0]
  delegate_to: "{{ delegate_node }}"

- name: Check API availability of master
  uri:
    url: "https://{{ ansible_host }}:6443"
    method: GET
    validate_certs: False
  register: k8s_api_result
  failed_when: false
  retries: 6
  delay: 15
  until: k8s_api_result is not failed
  delegate_to: "{{ delegate_node }}"