---
- name: Load kernel module
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - aufs
    - overlay
    - br_netfilter # 装不上
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack
    - rbd
  ignore_errors: true

- name: Set vm.swappiness=0
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "0"
    state: present

- name: Set vm.max_map_count=655360
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "655360"
    state: present

- name: Set net.bridge.bridge-nf-call-iptables=1
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present

- name: Set net.ipv4.ip_forward=1
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Disable swapoff permanently
  lineinfile:
    path: /etc/fstab
    regexp: "swap"
    state: absent
    backup: "yes"

# - name: Drain swap
#   command: "swapoff -a"
#   when: true

- name: System module load
  service:
    name: systemd-modules-load
    enabled: yes

- name: Kernel module load on boot
  copy:
    src: k8s-modules.conf
    dest: /etc/modules-load.d/k8s-modules.conf
    force: no
    mode: u+rw,g=r,o=r

- name: Add or modify nofile soft/hard limit
  community.general.pam_limits:
    domain: "*"
    limit_type: "-"
    limit_item: nofile
    value: "100000"

- name: Add or modify core soft/hard limit
  community.general.pam_limits:
    domain: "*"
    limit_type: "-"
    limit_item: core
    value: infinity

- name: Add or modify nproc soft/hard limit
  community.general.pam_limits:
    domain: "*"
    limit_type: "-"
    limit_item: nproc
    value: "100000"
